json.extract! @company, :id,
                        :name,
                        :street_address,
                        :city,
                        :state,
                        :zip,
                        :media_url,
                        :description,
                        :business_plan,
                        :founders,
                        :investors,
                        :offerings
